### ISSUE TITLE
Some mirrors? Cannot download from GitHub.

### ISSUE THREAD

**Issue by savely-krasovsky** [garbear/kodi-steamlink#12]
Can't download from GitHub. Speed from various regions (tested via VPN) starts from 30 kb/s and drops to nearly zero, then "Error: Access Denied". 
![image](https://user-images.githubusercontent.com/5345489/33437690-cc971e06-d5f9-11e7-94f1-8472eaa1d515.png)

**Comment by garbear** [comment]
I have to disable my VPN when I'm doing large GitHub syncs. Try without a VPN. Regardless, I'm uploading the 17.5 build to google drive now

EDIT: Here it is: https://drive.google.com/open?id=1gJg5wkwlmOKRlmg_jK_oFBa_6BHJkDUe

**Comment by savely-krasovsky** [comment]
I think it was Amazon Storage (that GitHub uses) issue. So now downloads properly. Anyway thanks for mirror!
