### ISSUE TITLE
Does not start with beta 605

### ISSUE THREAD

**Issue by Gomez** [garbear/kodi-steamlink#2]
After the update (for me today) Kodi does not start anymore. It get back to the link menu and says "Connecting to network". Was working with version 600 (at least starting, need to do more testing).

@garbear Thanks for this app!

**Comment by garbear** [comment]
Welcome :) I've informed Valve of this bug. I was able to test the interstitial firmwares and found that it actually broke between 602 and 603. Hopefully we can get this fixed soon. Thanks for the report!

**Comment by garbear** [comment]
Fixed in https://github.com/ValveSoftware/steamlink-sdk/pull/84
