### ISSUE TITLE
18 Alpha 2 "Release"

### ISSUE THREAD

**Issue by peterstory** [garbear/kodi-steamlink#22]
I'm interested in testing 18 Alpha 2 on my Steam Link (in particular, because 18's support for DRM will make it possible to watch Amazon videos! https://github.com/Sandmann79/xbmc#inputstream). How would I go about creating a `.zip` file, suitable for installing on my Steam Link? 

Also, are there any known issues with 18 Alpha 2 on Steam Links? If so, I have some interest in helping out (I'm a software developer, though my C++ skills are rusty).

**Comment by garbear** [comment]
As you can see, I've updated the Steam Link patch to 18 alpha 2: https://github.com/garbear/kodi-steamlink/tree/steamlink-18alpha2

However, I had to rewrite the entire windowing code from scratch, and haven't finished input yet so you can't control Kodi.

Also, VideoPlayer has changed a lot and I haven't finished updating the video decoder, so no HD decoding ATM.

So that's the state of 18 alpha2. I hope to finish updating by the time we reach Beta 1, which is in a few weeks.

**Comment by peterstory** [comment]
Wow, nice work! I hadn't realized how much work was involved in getting Kodi on the Steam Link! Well, once things are at the point where user-testing would be helpful, just let me know if you'd like my help.

**Comment by forstjiri** [comment]
I am looking for this release too, i want to test if Netflix is gonna work.
https://github.com/asciidisco/plugin.video.netflix

**Comment by garbear** [comment]
All in good time :) I got stuck trying to get keyboard and controller input to work (not much use otherwise). I'm not able to test for the nest few weeks, but my goal is a same day release with v18 final (probably a month or two)

**Comment by toXel** [comment]
@garbear So how can I build 18 beta 1? The instructions from the Valve repo aren't working for 18, right?

**Comment by garbear** [comment]
Right. I've finished porting Kodi to v18, but not working is input and hardware-accelerated video. Without input it's a bit pointless, but you can build using steamlink-beta1 branch (https://github.com/garbear/kodi-steamlink/commits/steamlink-18beta1) and the kodi-18beta1 branch (https://github.com/garbear/steamlink-sdk/commits/kodi-18beta1).

I'm still aiming to finish the v18 port by release. I'm traveling for Kodi and VLC's devcons the next two weeks, but there should be a bit of time left over to work on this.

**Comment by toXel** [comment]
Thanks for the status update :blush: yea without input it's a bit pointless to build it :smile:. I'll wait till this works. Have a good time at the cons!

**Comment by garbear** [comment]
I'm back in america and spent 2 days updating the build to beta 3. It now build and runs, but I'm still working on debugging input. I'll let you know when controllers are working again.

**Comment by garbear** [comment]
I fixed controller input on my `steamlink-18beta3` branch and `kodi-18beta3` steamlink sdk branch. It requires https://github.com/xbmc/peripheral.joystick/pull/155. Now all that's left is video decoding (my priority) and keyboard input. I'll upload some builds without HD video support so we can test everything else (I'm interested in getting Kodi's emulators working).

**Comment by garbear** [comment]
Unfortunately over the years, Kodi had gotten more resource-intensive, and the steam link is no longer a viable Kodi platform for performance reasons.
