### ISSUE TITLE
Kodi 17.6 doesn't start, v17.5 is working well

### ISSUE THREAD

**Issue by FranklinMaQ** [garbear/kodi-steamlink#27]
Hi @garbear !

First, what I want to say is - I really appreciate your hard work developing Kodi for Steam Link. This is awesome.

When I tried latest Kodi 17.6 - I can't get it to run, Running from Steam Link menu shows black screen for 2-4 seconds, then Steam Link main menu is visible (no device reboot I guess). I've also tried launching it from console, here is the exception:

`lsb_release: not found
lsb_release: not found
lsb_release: not found
ERROR: Unable to create application. Exiting`

And here is kodi.log file

`19:59:00.064 T:3001257984  NOTICE: -----------------------------------------------------------------------
19:59:00.268 T:3001257984   DEBUG: ConsoleKit.Manager: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.ConsoleKit was not provided by any .service files
19:59:00.269 T:3001257984   DEBUG: UPower: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
19:59:00.270 T:3001257984   DEBUG: ConsoleKit.Manager: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.ConsoleKit was not provided by any .service files
19:59:00.271 T:3001257984   DEBUG: DeviceKit.Power: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.DeviceKit.Disks was not provided by any .service files
19:59:00.271 T:3001257984   DEBUG: UPower: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
19:59:00.300 T:3001257984  NOTICE: load settings...
19:59:00.307 T:3001257984   ERROR: CSettings: error loading settings definition from special://xbmc/system/settings/settings.xml, Line 0
                                            Failed to open file
19:59:00.307 T:3001257984   FATAL: Unable to load settings definitions`

Also, it looks like deployment time of tgz archieve is shorter then 2 minutes. 
When I tried earlier builds (17,5 and 17.4) - Kodi boots fine, I just can't boot into latest version.

 Maybe you have some tips for me, what I can do or check? :)

**Comment by garbear** [comment]
This looks like the archive is truncated or missing files. The `lsb_release` error is a red herring, I get this too - it doesn't affect anything material.

The real error is:

```
ERROR: CSettings: error loading settings definition from special://xbmc/system/settings/settings.xml, Line 0 Failed to open file
FATAL: Unable to load settings definitions
```

Your settings.xml is missing or Kodi is looking in the wrong directory.
