### ISSUE TITLE
Please change "Unable to access USB devices" to "Unable to access mass storage USB devices"

### ISSUE THREAD

**Issue by Nowaker** [garbear/kodi-steamlink#30]
The "known issues" section at https://github.com/garbear/kodi-steamlink/releases is extremely scary due to:

> Unable to access USB devices

My thoughts: how am I supposed to use Kodi if mouse, keyboard or gamepad won't work?!

Then it turned out it's about reading data from USB devices.

**Comment by garbear** [comment]
Haha good point. Will update.
