### ISSUE TITLE
can not copy because filesystem doesn't support symlinks

### ISSUE THREAD

**Issue by splace** [garbear/kodi-steamlink#5]
get this when following installation instructions.

**Comment by garbear** [comment]
Can you be more specific? What did you do to create this error message? Can you outline the steps so I can reproduce the problem?

**Comment by splace** [comment]
i tried to copy the unpacked kodi, (kodi-17.3-2017-05-28), onto a fat32 formatted drive.
it has a symlnk so i got this error message.
i reformatted to ext4 and it worked.

**Comment by garbear** [comment]
The steamlink supports apps that are packed or unpacked. If you have a fat32 drive, you can copy the archive without unpacking and the SL will automatically unpack upon installation.

I'll close this issue, you can reopen it if you have any other questions.
