### ISSUE TITLE
Audio delay on any live stream

### ISSUE THREAD

**Issue by quendera** [garbear/kodi-steamlink#6]
First of all thank you very much for all the work put into kodi on the SL.

As the stream starts it loads black with sound, play for 5-10 seconds and the video plays so the audio is massively behind which is strange because the video performance is flawless.

Issue happens on h264 streams regardless of resolution and the used app (happens on YT, Twitch and even IPT). Audio delay adjustement does not fix it.

Running latest steamlink build and kodi 17.3

**Comment by garbear** [comment]
Thanks for the report. I'll look into this over the weekend.

**Comment by quendera** [comment]
Please let me know what I can do to help.

**Comment by garbear** [comment]
Can you try local playback of HD h264 content? That would narrow down the bug to just online streams

**Comment by quendera** [comment]
Apologies for the delay.  

Local playback of SD and HD h264 does not cause the issue.
I find the issue on youtube, youtube livestream, sports streams, twitch.tv and exodus. 

The issue is not fixable by manually controlling audio delay...

**Comment by Sonic198** [comment]
Hi @garbear , is there any fix for that? I have the same issue on v17.6. Sports streams have delays only on steam link (no issue on PC). Or maybe this is fixes in v18?
