### ISSUE TITLE
App not showing up in the home menu

### ISSUE THREAD

**Issue by Sclafus** [garbear/kodi-steamlink#7]
I followed all the instructions, the installation part was flowless but nothing happened... The menu had no kodi button
Any fix?

**Comment by garbear** [comment]
Have you tried both the Public and Beta firmware? Are you sure it was installed? It should add at least a minute to the boot process. Can you ssh into the box and verify that Kodi exists on the storage?

I'm not sure how to fix this, but those questions will be a good place to start.

**Comment by Sclafus** [comment]
I tried both, but there were no updates when i switched. I tried the same process with the same file and nothing happened, so i assumed it was already installed. It took a minute to boot up after the installation. I've not tried to ssh into the box, how can I do it?

**Comment by garbear** [comment]
> so i assumed it was already installed

If the file is present on the USB drive, it will always reinstall and overwrite the existing app. If the startup process isn't taking ~2mins, then the 80MB archive isn't installing on startup.

I assume you're using a FAT partition? Can you try EXT4? Maybe reformatting with a different tool will help, sometimes formatters can include extra boot partitions or something that could throw off the steam link.

**Comment by Sclafus** [comment]
Ok solved! I took the power cable out, inserted the usb with kodi and enable_ssh file, plugged it in and now it's working just fine! Thanks for your support ♥

**Comment by ghost** [comment]
Having the same issue now, but whatever i try im not getting it fixed :(
- Tried normal and beta SL firmware
- Tried 2 different usb sticks (one usb2 one usb3) in FAT32
- Tried all 3 usb ports on the SL
- Tried to enable ssh as described, trying to connect gets me 'connection refused' :[

Last thing i can do now (as per the suggestion above) is maybe EXT4 filesystem? but how even? im a windows user >_>

Any other ideas?

Edit: forgot to mention i also made sure that the SL detects the 2 usb sticks i used, they show up as usb drives just fine, the SL just doesnt do anything with them.
